name = "dc256-victim-game"
compatibility_date = "2026-04-16"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "GAME_DB"
database_name = "dc256-victim-game"
database_id = "replace-with-cloudflare-d1-database-id"
